server:
  port: 8888

spring:
  application:
    name: config-server
# config of config server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aalache/config-repo.git
          default-label: master

